### ISSUE TITLE
RHEL 7.3 beta error - crashes install

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/oscap-anaconda-addon#8]
![image](https://cloud.githubusercontent.com/assets/5713754/18133602/443aa9bc-6f69-11e6-9be4-390a15364f24.png)

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/18133629/608f1ee0-6f69-11e6-945a-99e8c2ae2d82.png)

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/18133659/7606c9bc-6f69-11e6-898d-c530b485fc2a.png)

**Comment by shawndwells** [comment]
appears to be https://bugzilla.redhat.com/show_bug.cgi?id=1360765

**Comment by ybznek** [comment]
It is probably fixed by https://github.com/OpenSCAP/oscap-anaconda-addon/commit/fb9c485418e59cfead3ab28d8ff8cfb7a19bba48

(Referenced bz bugs are duplicates.)

I think it fix current issues, because we currently reference only remote OVAL which is not necessary for "remediate"/"generate_fix".

If some content reference XCCDF then it will not work with such current fix. We probably need a checkbox to enable fetching of remote resources.

**Comment by pysysops** [comment]
Interesting. I'm encountering a similar error. I think it's because I'm trying to build a machine with no proxy set or route to the internet. Am I right in thinking that the addon calls out to the internet to get up to date oval / security info from redhat.com? 

Is there any way to supply it to the ks file as a file on the local fs?

I'm trying to make use of oscap to secure and report on servers from day 0 (image creation pipeline). 

Any help or advice would be really appreciated. Thanks!

**Comment by shawndwells** [comment]
This was fixed downstream for RHEL 7.4 release. Closing this.
